config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get 'home/about' => 'homes#about', as:"about"

  resources :books, only: [:index, :show, :edit, :update, :create, :destroy]
  resources :users, only: [:index, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  #has_one_attached :image

  validates :title, presence:true
  validates :body, presence:true, length: { maximum:200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, uniqueness:true, length: { in:2..20 }
  validates :introduction, length: { maximum:50 }


 def get_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :correct_user, only: [:edit, :update]
# 以下を追加
  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    # UserIDを取り出す
    @book.user_id = current_user.id
    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @book.save
    # 画面へリダイレクトし、フラッシュメッセージを表示させる
    flash[:notice] = "You have created book successfully."
    # 4. トップ画面へリダイレクト
    redirect_to book_path(@book)

    else
    @user = current_user
    @books = Book.all
    render :index
    end
  end


  def index
     @book = Book.new
     @user = current_user
     @books = Book.all
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end


  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def create
     # １.&2. データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    # UserIDを取り出す
    @book.user_id = current_user.id
    # 3. データをデータベースに保存するためのsaveメソッド実行
    @book.save
    # 4. トップ画面へリダイレクト
    redirect_to books_path(@book)
  end

  def index
     @book = Book.new
     @user = current_user
     @users = User.all
  end

  def show
    @book_new = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    # 3. フラッシュメッセージを定義し、詳細画面へリダイレクト
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user.id)
    else
     render :edit
    end
  end

   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user)) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">

    <h2>User info</h2>
     <%= image_tag user.get_image(100,100) %>
     <table class="table">
      <tbody>
        <tr>
         <th>name</th>
         <th><%= user.name %></th>
        </tr>
        <tr>
         <th>introduction</th>
         <th><%= user.introduction %></th>
        </tr>

      </tbody>
     </table>

     <%= link_to edit_user_path(user.id), class:'btn btn-outline-secondary btn-block edit_user_77129' do%>
      <i class="fas fa-user-cog"></i>
      <%end%>


    <h2 class="mt-3">New book</h2>
     <%= form_with model: book do |f| %>

     <div class="form-group">
      <p>Title</p>
       <%= f.text_field :title %>
      </div>

     <div class="form-group">
      <p>Opinion</p>
        <%= f.text_area :body %>
     </div>

     <div>
       <%= f.submit 'Create Book', class: 'btn btn-success' %>
     </div>
     <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>

       <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <ul>
       <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
       <% end %>
       </ul>
       <% end %>

      <%= form_with model: @book do |f| %>

      <div class="form-group">
      <P>Title</P>
      <%= f.text_field :title %>
      </div>

      <div class="form-group">
      <P>Opinion</p>
      <%= f.text_area :body %>
      </div>


      <%= f.submit "Update Book", class: 'btn btn-success' %>

      <% end %>

      <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 <div class="row">
  <div class="col-md-3">

    <h2>User info</h2>
     <%= image_tag @user.get_image(100,100) %>
     <table class="table">
      <tbody>
        <tr>
         <th>name</th>
         <th><%= @user.name %></th>
        </tr>
        <tr>
         <th>introduction</th>
         <th><%= @user.introduction %></th>
        </tr>

      </tbody>
     </table>

     <%= link_to edit_user_path(@user.id), class:'btn btn-outline-secondary btn-block edit_user_77129' do%>
      <i class="fas fa-user-cog"></i>
      <%end%>


    <h2 class="mt-3">New book</h2>
     <%= form_with model: @book do |f| %>

     <div class="form-group">
      <p>Title</p>
       <%= f.text_field :title %>
      </div>

     <div class="form-group">
      <p>Opinion</p>
        <%= f.text_area :body %>
     </div>

     <div>
       <%= f.submit 'Create Book', class: 'btn btn-success' %>
     </div>
     <% end %>
   </div>

   <div class="col-md-8 offset-md-1">
     <h2>Books</h2>

    <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
       </tr>
       </thead>
       <tbody>
       <% @books.each do |book| %>
       <tr>
         <td><%= link_to user_path(book.user.id) do%>
         <%= image_tag book.user.get_image(100,100) %>
         <%end%>
         </td>
         <td>
         <%= link_to book.title, book_path(book.id) %>
          </td>
         <td><%= book.body %></td>
       </tr>
       <%end%>
       </tbody>
    </table>
   </div>

 </div>
 </div>

app/views/books/show.html.erb
<%= render 'list', book: @book_new, user: @user %>

   <div class="col-md-8 offset-md-1">
     <h2>Book detail</h2>

    <table class="table table-hover table-inverse">

       <tr>
         <td><%= link_to user_path(@user.id) do %><%= image_tag @user.get_image(100,100) %><br><%= @user.name %><%end%></td>
         <td>
         <%= link_to @book.title, book_path(@book.id) %>
          </td>
         <td><%= @book.body %></td>

         <% if @user == current_user %>
         <td><%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-sm btn-success edit_book_58920' %></td>
         <td><%= link_to 'Destroy', book_path(@book.id), method: :delete,  class: 'btn btn-sm btn-danger destroy_book_58920', "data-confirm" => "本当に消しますか？"%></td>
         <%end%>
       </tr>
    </table>
   </div>

 </div>
 </div>

app/views/homes/about.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3'%>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block'%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

      <a href="/" class="navbar-brand" >
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

    <% if user_signed_in? %>
      <li>
        <%= link_to user_path(current_user), class: 'nav-link text-light' do%>
        <i class="fas fa-home"></i> Home
        <%end%>
      </li>
      <li>
        <%= link_to  users_path, class: 'nav-link text-light' do%>
        <i class="fas fa-users"></i> Users
        <%end%>
      </li>
      <li>
        <%= link_to books_path, class: 'nav-link text-light' do%>
        <i class="fas fa-book-open"></i> Books
        <%end%>
      </li>
      <li>
       <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
       <i class="fas fa-sign-out-alt"></i> Log out
       <% end %>

      </li>
    <% else %>
      <li>
        <%= link_to root_path, class: 'nav-link text-light' do%>
        <i class="fas fa-home"></i> Home
        <%end%>
      </li>
      <li>
        <%= link_to about_path, class: 'nav-link text-light' do%>
        <i class="fas fa-link"></i> About
        <%end%>
      </li>
      <li>
        <%= link_to new_user_registration_path, class: 'nav-link text-light' do%>
        <i class="fas fa-user-plus"></i> Sign up
        <%end%>
      </li>
      <li>
        <%= link_to new_user_session_path, class: 'nav-link text-light' do%>
        <i class="fas fa-sign-in-alt"></i> Log in
        <%end%>
      </li>
    <% end %>
    </ul>
    </div>
    </nav>
  </header>
  <main>
    <!--<p class="notice"></p>-->
    <div>
  <%= flash[:notice] %>
   </div>

    <%= yield %>
  </main>
  <footer>
    <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
    </div>
  </footer>
</body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

    <h2>User info</h2>

     <% if @user.errors.any? %>
     <%= @user.errors.count %>errors prohibited this obj from being saved:
     <ul>
     <% @user.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
     </ul>
     <% end %>

      <%= form_with model: @user do |f| %>

      <div class="form-group">
      <p>Name</p>
      <%= f.text_field :name %>
      </div>

      <div class="form-group">
      <p>Image</p>
      <%= f.file_field :profile_image, accept: "image/*" %>
      </div>

      <div class="form-group">
      <p>Introduction</p>
      <%= f.text_area :introduction %>
      </div>

      <%= f.submit "Update User", class: 'btn btn-secondary' %>

      <% end %>

  </div>
 </div>
</div>

app/views/users/index.html.erb
　<%= render 'books/list', book: @book, user: @user %>

   <div class="col-md-8 offset-md-1">
     <h2>Users</h2>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
       </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
       <tr>
         <td><%= image_tag user.get_image(100,100) %></td>
         <td><%= user.name %></td>
         <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
       <%end%>
       </tbody>
    </table>
   </div>

 </div>
 </div>

app/views/users/show.html.erb
<%= render 'books/list', book: @book_new, user: @user %>

<div class="col-md-8 offset-md-1">
     <h2>Books</h2>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
       </tr>
      </thead>
      <tbody>
       <% @books.each do |book| %>
       <tr>
         <td>
           <%= link_to user_path(book.user.id) do%>
           <%= image_tag book.user.get_image(100,100) %>
           <%end%>
         </td>
         <td>
         <%= link_to book.title, book_path(book.id) %>
          </td>
         <td><%= book.body %></td>
       </tr>
       <%end%>
      </tbody>
    </table>
   </div>

 </div>
 </div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>